### PR TITLE
Fixing search filters

### PR DESCRIPTION
**Pull request by BuckBuchanan**

### CODE REVIEW

**Comment by BuckBuchanan** [comment]
Hey, @jjbohn. This is identical to a change that was added to the main spree-multi-domain back on January 29th. The current code prevents ProductFilters from being used.

**Comment by jjbohn** [comment]
:+1:

**Comment by BuckBuchanan** [comment]
Thanks, @jjbohn. I don't have permission to merge this pull request, so whenever you get a chance, please merge it.

**Comment by BuckBuchanan** [comment]
Hey @jjbohn, I've added another bug fix to this pull request. Without this fix the list of stores for a product was getting reset to nil every time someone clicked the "Update" button on the product_properties#index page.

**Comment by jjbohn** [comment]
:+1:

**Pull request merged**
